### ISSUE TITLE
Relaunch the HOPRd operator and two new HOPR nodes

### ISSUE THREAD

**Issue by sitilge** [Rpc-h/applications#16]
The proposal and hence the task switching back again to HOPR operator was suggested by @ausias-armesto . 

As you can see in the image below, I re-created the HOPRd operator and two new HOPR nodes. The nodes fulfilled the startup probes after 49 minutes. However, they were not able to send/receive message until ~2h after spawning.

![image](https://github.com/Rpc-h/applications/assets/3306642/41d125ae-f77d-487f-a6ed-382fbcc6da61)

**Comment by ausias-armesto** [comment]
Please make more test from internal to external nodes and viceversa. Colllect all the data need it in case of problems so we can request a meeting with someone from the Core Team
